import { Project } from '@/types'

const projects: Project[] = [
  {
    id: '0',
    stack: [
      { name: 'Next.js 16' },
      { name: 'React 19' },
      { name: 'Typescript 5.9' },
      { name: 'Tailwind CSS 4' },
      { name: 'Framer Motion' },
      { name: 'Next-intl' },
      { name: 'Zod' },
      { name: 'React Hook Form' },
      { name: 'Radix UI' },
      { name: 'Sonner' },
      { name: 'Swiper' },
    ],
    video: '/assets/work/video/portfolio.webm',
    github: 'https://github.com/admitruk237/my-portfolio',
    live: 'https://andrii-portfolio-one.vercel.app/',
  },
  {
    id: '1',
    stack: [
      { name: 'React' },
      { name: 'Redux Toolkit' },
      { name: 'TypeScript' },
      { name: 'Axios' },
      { name: 'Context API' },
      { name: 'Custom Hooks' },
      { name: 'useRef' },
      { name: 'Vite' },
    ],
    image: '/assets/work/img/news.png',
    github: 'https://github.com/admitruk237/news-reactfy',
    live: 'https://news-reactfy.vercel.app/',
  },
  {
    id: '2',
    stack: [
      { name: 'Next.js' },
      { name: 'TypeScript' },
      { name: 'Tailwind CSS' },
      { name: 'ShadCN UI' },
      { name: 'REST API' },
      { name: 'Jest' },
      { name: 'React Toastify' },
      { name: 'Clean Architecture' },
      { name: 'DRY' },
    ],
    image: '/assets/work/img/quotes.png',
    github: 'https://github.com/admitruk237/Quotes-app',
    live: '',
  },
  {
    id: '3',
    stack: [
      { name: 'React' },
      { name: 'TypeScript' },
      { name: 'Redux' },
      { name: 'Framer Motion' },
      { name: 'Material UI' },
      { name: 'JWT' },
      { name: 'React Router' },
      { name: 'Unit Testing' },
      { name: 'Storybook' },
    ],
    video: '/assets/work/video/gtd.webm',
    github: 'https://github.com/admitruk237/Get-Task-Driver',
    live: '',
  },
  {
    id: '4',
    stack: [
      { name: 'React' },
      { name: 'Redux' },
      { name: 'Redux Toolkit' },
      { name: 'JavaScript' },
      { name: 'Express' },
      { name: 'Axios' },
      { name: 'Toastify' },
      { name: 'Node.js' },
      { name: 'REST API' },
      { name: 'Redux Toolkit Thunks' },
    ],
    video: '/assets/work/video/library.webm',
    github: 'https://github.com/admitruk237/Book-Library-App',
    live: '',
  },
  {
    id: '5',
    stack: [
      { name: 'Html 5' },
      { name: 'Css 3' },
      { name: 'Javascript' },
      { name: 'LocalStorage' },
      { name: 'Team Project' },
      { name: 'GitHub' },
      { name: 'Gulp' },
      { name: 'BEM' },
      { name: 'Sass' },
    ],
    video: '/assets/work/video/shopStore.webm',
    github: 'https://github.com/admitruk237/ShoppeStore',
    live: 'https://shoppestore.netlify.app/',
  },
  {
    id: '6',
    stack: [
      { name: 'Html 5' },
      { name: 'Css 3' },
      { name: 'Javascript' },
      { name: 'Responsive Design' },
      { name: 'BEM' },
      { name: 'Figma' },
      { name: 'Accordion Component' },
      { name: 'Smooth Navigation' },
    ],
    video: '/assets/work/video/homePro.webm',
    github: 'https://github.com/admitruk237/Home-Pro',
    live: 'https://admitruk237.github.io/Home-Pro/',
  },
  {
    id: '7',
    stack: [
      { name: 'Html 5' },
      { name: 'Css 3' },
      { name: 'Sass' },
      { name: 'BEM' },
      { name: 'Javascript' },
      { name: 'Responsive Design' },
      { name: 'Animations' },
      { name: 'Parallax Effects' },
      { name: 'Figma' },
    ],
    video: '/assets/work/video/farm.webm',
    github: 'https://github.com/admitruk237/Farm-Vest',
    live: 'https://admitruk237.github.io/Farm-Vest/',
  },
  {
    id: '8',
    stack: [
      { name: 'Html 5' },
      { name: 'Css 3' },
      { name: 'Javascript' },
      { name: 'Sass' },
      { name: 'BEM' },
      { name: 'Gulp' },
      { name: 'Responsive Design' },
      { name: 'Figma' },
    ],
    video: '/assets/work/video/corona.webm',
    github: 'https://github.com/admitruk237/GoCorona',
    live: 'https://go-corona-umber.vercel.app/',
  },
  {
    id: '9',
    stack: [
      { name: 'Html 5' },
      { name: 'Css 3' },
      { name: 'Javascript' },
      { name: 'Sass' },
      { name: 'BEM' },
      { name: 'Responsive Design' },
      { name: 'Figma' },
    ],
    video: '/assets/work/video/finance.webm',
    github: 'https://github.com/admitruk237/Finance-site',
    live: 'https://admitruk237.github.io/Finance-site/',
  },
  {
    id: '10',
    stack: [
      { name: 'Html 5' },
      { name: 'Css 3' },
      { name: 'Javascript' },
      { name: 'Sass' },
      { name: 'BEM' },
      { name: 'Responsive Design' },
      { name: 'Figma' },
    ],
    video: '/assets/work/video/interia.webm',
    github: 'https://github.com/admitruk237/I-N-T-E-R-I-A',
    live: 'https://admitruk237.github.io/I-N-T-E-R-I-A/',
  },
]

export { projects }
export default projects
