import type { ProjectPreview, Project } from '@/types'
import { githubRepoUrl, personalRepoUrl } from './profile'

const VIDEO_DIR = '/assets/work/video'
const IMAGE_DIR = '/assets/work/img'

const video = (fileName: string): ProjectPreview => ({
  kind: 'video',
  src: `${VIDEO_DIR}/${fileName}`,
})

const image = (fileName: string): ProjectPreview => ({
  kind: 'image',
  src: `${IMAGE_DIR}/${fileName}`,
})

export const PROJECTS: Project[] = [
  {
    id: 'megaWin',
    category: 'internship',
    stack: [
      'Next.js 16',
      'React 19',
      'TypeScript',
      'Zustand',
      'TanStack Query',
      'Axios',
      'React Hook Form',
      'Zod',
      'Tailwind CSS 4',
      'shadcn/ui',
      'Base UI',
      'Motion',
      'Sonner',
      'FSD Architecture',
      'ESLint Boundaries',
      'Jest',
      'React Testing Library',
      'Husky',
      'Prettier',
    ],
    preview: video('megaWin.webm'),
    githubUrl: githubRepoUrl('MegaWin-Evoverse', 'mega-win'),
    liveUrl: 'https://mega-win.vercel.app',
  },
  {
    id: 'houseCrm',
    category: 'commercial',
    stack: [
      'Next.js 16',
      'Redux Toolkit',
      'TypeScript',
      'RTK Query',
      'FSD Architecture',
      'TanStack Table',
      'Shadcn UI',
      'Recharts',
      'Framer Motion',
      'React PDF',
      'React Hook Form',
      'Lucide React',
      'Yup / Zod',
      'Storybook',
      'Vitest',
      'Playwright',
      'ESLint 9',
      'NestJS',
    ],
    preview: video('houseCRM.webm'),
    githubUrl: githubRepoUrl('San88Francisco', 'HousesCRM'),
    liveUrl: 'https://houses-crm.vercel.app',
  },
  {
    id: 'portfolio',
    category: 'next',
    stack: [
      'Next.js 16',
      'React 19',
      'Typescript 5.9',
      'Tailwind CSS 4',
      'Framer Motion',
      'Next-intl',
      'Zod',
      'React Hook Form',
      'Radix UI',
      'Sonner',
      'Swiper',
    ],
    preview: video('portfolio.webm'),
    githubUrl: personalRepoUrl('my-portfolio'),
    liveUrl: 'https://andrii-portfolio-one.vercel.app/',
  },
  {
    id: 'newsReactfy',
    category: 'react',
    stack: [
      'React',
      'Redux Toolkit',
      'TypeScript',
      'Axios',
      'Context API',
      'Custom Hooks',
      'useRef',
      'Vite',
    ],
    preview: image('news.png'),
    githubUrl: personalRepoUrl('news-reactfy'),
    liveUrl: 'https://news-reactfy.vercel.app/',
  },
  {
    id: 'quotesApp',
    category: 'next',
    stack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'ShadCN UI',
      'REST API',
      'Jest',
      'React Toastify',
      'Clean Architecture',
      'DRY',
      'OpenAPI',
    ],
    preview: image('quotes.png'),
    githubUrl: personalRepoUrl('Quotes-app'),
  },
  {
    id: 'getTaskDriver',
    category: 'react',
    stack: [
      'React',
      'TypeScript',
      'Redux',
      'Framer Motion',
      'Material UI',
      'JWT',
      'React Router',
      'Unit Testing',
      'Storybook',
    ],
    preview: video('gtd.webm'),
    githubUrl: personalRepoUrl('Get-Task-Driver'),
  },
  {
    id: 'bookLibrary',
    category: 'react',
    stack: [
      'React',
      'Redux',
      'Redux Toolkit',
      'JavaScript',
      'Express',
      'Axios',
      'Toastify',
      'Node.js',
      'REST API',
      'Redux Toolkit Thunks',
    ],
    preview: video('library.webm'),
    githubUrl: personalRepoUrl('Book-Library-App'),
  },
  {
    id: 'shopStore',
    category: 'ecommerce',
    stack: [
      'Html 5',
      'Css 3',
      'Javascript',
      'LocalStorage',
      'Team Project',
      'GitHub',
      'Gulp',
      'BEM',
      'Sass',
    ],
    preview: video('shopStore.webm'),
    githubUrl: personalRepoUrl('ShoppeStore'),
    liveUrl: 'https://shoppestore.netlify.app/',
  },
  {
    id: 'homePro',
    category: 'landing',
    stack: [
      'Html 5',
      'Css 3',
      'Javascript',
      'Responsive Design',
      'BEM',
      'Figma',
      'Accordion Component',
      'Smooth Navigation',
    ],
    preview: video('homePro.webm'),
    githubUrl: personalRepoUrl('Home-Pro'),
    liveUrl: 'https://admitruk237.github.io/Home-Pro/',
  },
  {
    id: 'farmVest',
    category: 'landing',
    stack: [
      'Html 5',
      'Css 3',
      'Sass',
      'BEM',
      'Javascript',
      'Responsive Design',
      'Animations',
      'Parallax Effects',
      'Figma',
    ],
    preview: video('farm.webm'),
    githubUrl: personalRepoUrl('Farm-Vest'),
    liveUrl: 'https://admitruk237.github.io/Farm-Vest/',
  },
  {
    id: 'goCorona',
    category: 'landing',
    stack: [
      'Html 5',
      'Css 3',
      'Javascript',
      'Sass',
      'BEM',
      'Gulp',
      'Responsive Design',
      'Figma',
    ],
    preview: video('corona.webm'),
    githubUrl: personalRepoUrl('GoCorona'),
    liveUrl: 'https://go-corona-umber.vercel.app/',
  },
  {
    id: 'finance',
    category: 'landing',
    stack: [
      'Html 5',
      'Css 3',
      'Javascript',
      'Sass',
      'BEM',
      'Responsive Design',
      'Figma',
    ],
    preview: video('finance.webm'),
    githubUrl: personalRepoUrl('Finance-site'),
    liveUrl: 'https://admitruk237.github.io/Finance-site/',
  },
  {
    id: 'interia',
    category: 'landing',
    stack: [
      'Html 5',
      'Css 3',
      'Javascript',
      'Sass',
      'BEM',
      'Responsive Design',
      'Figma',
    ],
    preview: video('interia.webm'),
    githubUrl: personalRepoUrl('I-N-T-E-R-I-A'),
    liveUrl: 'https://admitruk237.github.io/I-N-T-E-R-I-A/',
  },
]
