import { JetBrains_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';
import PageTransition from '@/components/PageTransition/PageTransition';
import StairTransition from '@/components/StairTransition/StairTransition';
import { Toaster } from '@/components/ui/sonner';

const jetBrainsMono = JetBrains_Mono({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Andrii portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable} suppressHydrationWarning={true}>
        <Header />
        <Toaster />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
